name: "apply Harvester sshd_config"
stages:
   initramfs:
     - name: "remove SL Micro 5.x ssh and sshd config"
       commands:
       - |
         # remove config files that will be here on systems
         # upgrade from Harvester before v1.7.0, which would
         # otherwise completely override the system default
         # config file /usr/etc/ssh/sshd_config
         rm -f /etc/ssh/sshd_config
         # same for /usr/etc/ssh/ssh_config
         rm -f /etc/ssh/ssh_config
