name: "apply Harvester lvm config"
stages:
   initramfs:
     - name: "patch lvm config (filter out loop/longhorn device)"
       commands:
       - |
        sed -i 's/^devices.*/&\n\tglobal_filter = [ "r|\/dev\/loop.*|", "r|\/dev\/disk\/by-path\/.*longhorn.*|" ]/' /etc/lvm/lvm.conf
     - name: "patch udev_sync, udev_rules on lvm config"
       commands:
       - |
        sed -i 's/# udev_sync = 1/udev_sync = 0/' /etc/lvm/lvm.conf
        sed -i 's/# udev_rules = 1/udev_rules = 0/' /etc/lvm/lvm.conf
        sed -i 's/# auto_set_activation_skip = 1/auto_set_activation_skip = 0/' /etc/lvm/lvm.conf