# start an nginx server to server ISO content if
# - `harvester.serve_iso=true` is in kernel parameters, or
# - `/harvester-serve-iso` file exists
name: "serve iso content"
stages:
  initramfs:
    - if: grep -q harvester.serve_iso=true /proc/cmdline || [ -e /harvester-serve-iso ]
      directories:
      - path: /var/log/nginx
        permissions: 0664
      commands:
      - |
        # Let NetworkManager bring up all connected interfaces with DHCP
        # automatically for the ISO repo
        if [ -e /etc/NetworkManager/conf.d/harvester.conf ] ; then
          sed -i '/^no-auto-default=\*/d' /etc/NetworkManager/conf.d/harvester.conf
        fi
      - cp /etc/nginx/conf.d/iso.conf.disabled /etc/nginx/conf.d/iso.conf
      - systemctl enable nginx
