[main]
# Don't do automatic DHCP configuration of ethernet devices
# without connection profiles
no-auto-default=*

# Ignore carrier (cable plugged in) when attempting to
# activate static IP connections
ignore-carrier=*
