on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  IMAGE_NAME: rancher/harvester-os:v1.4-20250211
  TEST_TAG: v1.4-20250211

jobs:
  create-installer-pr:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.5
    steps:
      - name: Set up GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.66.1/gh_2.66.1_linux_amd64.tar.gz -o ghcli.tar.gz
          tar xzf ghcli.tar.gz
          mv gh_2.66.1_linux_amd64/bin/gh /usr/local/bin/
          gh --version
      - name: fetch-target-version
        run: |
          echo "targetVersion=$(echo ${{ env.TEST_TAG }} | cut -d'-' -f1)" >> $GITHUB_ENV
      - name: Install docker
        run: zypper ref && zypper -n install docker npm git
      - name: Pull release image
        run: |
          docker pull ${{ env.IMAGE_NAME }}
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Get current OS image from installer
        run: |
          curl -sfL https://raw.githubusercontent.com/harvester/harvester-installer/${{ env.targetVersion }}/scripts/package-harvester-os -o /tmp/package-harvester-os
          grep '^BASE_OS_IMAGE="rancher/harvester-os:' /tmp/package-harvester-os > /tmp/tmp-env
      - name: Run container-diff
        run: |
          source /tmp/tmp-env
          docker pull $BASE_OS_IMAGE
          echo "Diff $BASE_OS_IMAGE with ${{ env.IMAGE_NAME }}..."
          container-diff diff daemon://docker.io/$BASE_OS_IMAGE daemon://docker.io/${{ env.IMAGE_NAME }} --type=rpm --output=/tmp/diff-result.txt
          cat /tmp/diff-result.txt
      - name: Clone harvester-installer repo
        uses: actions/checkout@v3
        with:
          repository: harvester/harvester-installer
          ref: ${{ env.targetVersion }}
      - name: Update os image
        run: sed -i "s,^BASE_OS_IMAGE=.*,BASE_OS_IMAGE=\"${{ env.IMAGE_NAME }}\"," scripts/package-harvester-os
      - name: Config PR committer
        run: |
          git config --global user.email "<noreply@github.com>"
          git config --global user.name "Github"
      - name: Create PR Content
        run: |
          {
            echo "prContent<<EOF"
            echo "**Problem:**"
            echo "Harvester base OS needs to update."
            echo ""
            echo "**Solution:**"
            echo "Bump OS image to [${{ env.IMAGE_NAME }}](https://github.com/harvester/os2/releases/tag/${{ env.TEST_TAG }})."
            echo ""
            echo "**Related Issue:**"
            echo ""
            echo "**Test plan:**"
            echo ""
            echo "**More info:**"
            echo '~~~'
            cat /tmp/diff-result.txt
            echo '~~~'
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Create installer PR
        run: |
          echo "${{ env.prContent }}"