name: Package Differences

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

env:
  OS_IMAGE_v1_8_x: registry.opensuse.org/isv/rancher/harvester/os/v1.8/main/baseos:latest
  OS_IMAGE_v1_7_x: registry.opensuse.org/isv/rancher/harvester/os/v1.7/main/baseos:latest
  OS_IMAGE_v1_6_x: registry.opensuse.org/isv/rancher/harvester/os/v1.6/main/baseos:latest
  OS_IMAGE_v1_5_x: registry.opensuse.org/isv/rancher/harvester/os/v1.5/main/baseos:latest

jobs:
  get-all-releases:
    runs-on: ubuntu-latest
    outputs:
      releaseName_v1_8_x: ${{ steps.get_release_v1_8_x.outputs.releaseName }}
      releaseName_v1_7_x: ${{ steps.get_release_v1_7_x.outputs.releaseName }}
      releaseName_v1_6_x: ${{ steps.get_release_v1_6_x.outputs.releaseName }}
      releaseName_v1_5_x: ${{ steps.get_release_v1_5_x.outputs.releaseName }}

    steps:
      - name: Get all releases
        id: get_all_releases
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
            });
            
            const releases = response.data;
            core.setOutput('allReleases', releases);
      - name: Get v1.8 latest release
        id: get_release_v1_8_x
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const releases = ${{ steps.get_all_releases.outputs.allReleases }};
            const releaseNamePrefix = "v1.8";
            const foundRelease = releases.find(release => release.name.startsWith(releaseNamePrefix));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              core.setOutput('releaseName', releaseName);
            }
      - name: Get v1.7 latest release
        id: get_release_v1_7_x
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const releases = ${{ steps.get_all_releases.outputs.allReleases }};
            const releaseNamePrefix = "v1.7";
            const foundRelease = releases.find(release => release.name.startsWith(releaseNamePrefix));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              core.setOutput('releaseName', releaseName);
            }
      - name: Get v1.6 latest release
        id: get_release_v1_6_x
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const releases = ${{ steps.get_all_releases.outputs.allReleases }};
            const releaseNamePrefix = "v1.6";
            const foundRelease = releases.find(release => release.name.startsWith(releaseNamePrefix));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              core.setOutput('releaseName', releaseName);
            }
      - name: Get v1.5 latest release
        id: get_release_v1_5_x
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const releases = ${{ steps.get_all_releases.outputs.allReleases }};
            const releaseNamePrefix = "v1.5";
            const foundRelease = releases.find(release => release.name.startsWith(releaseNamePrefix));

            if (foundRelease) {
              const releaseName = foundRelease.name;
              core.setOutput('releaseName', releaseName);
            }

  fetch-v1-8-x-diff:
    needs: get-all-releases
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.5

    steps:
      - name: Set osImage
        id: set_os_image
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const osImage = `rancher/harvester-os:${{ needs.get-all-releases.outputs.releaseName_v1_8_x }}`;
            core.setOutput('osImage', osImage);
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Pull release image
        run: |
          docker pull ${{ steps.set_os_image.outputs.osImage }}
      - name: Run container-diff for v1.8.x
        run: |
          docker pull ${{ env.OS_IMAGE_v1_8_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_8_x }} with ${{ steps.set_os_image.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ steps.set_os_image.outputs.osImage }} daemon://docker.io/${{ env.OS_IMAGE_v1_8_x }} --type=rpm --output=diff-result.txt
          cat diff-result.txt

  fetch-v1-7-x-diff:
    needs: get-all-releases
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.5

    steps:
      - name: Set osImage
        id: set_os_image
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const osImage = `rancher/harvester-os:${{ needs.get-all-releases.outputs.releaseName_v1_7_x }}`;
            core.setOutput('osImage', osImage);
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Pull release image
        run: |
          docker pull ${{ steps.set_os_image.outputs.osImage }}
      - name: Run container-diff for v1.7.x
        run: |
          docker pull ${{ env.OS_IMAGE_v1_7_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_7_x }} with ${{ steps.set_os_image.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ steps.set_os_image.outputs.osImage }} daemon://docker.io/${{ env.OS_IMAGE_v1_7_x }} --type=rpm --output=diff-result.txt
          cat diff-result.txt

  fetch-v1-6-x-diff:
    needs: get-all-releases
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.5

    steps:
      - name: Set osImage
        id: set_os_image
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const osImage = `rancher/harvester-os:${{ needs.get-all-releases.outputs.releaseName_v1_6_x }}`;
            core.setOutput('osImage', osImage);
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Pull release image
        run: |
          docker pull ${{ steps.set_os_image.outputs.osImage }}
      - name: Run container-diff for v1.6.x
        run: |
          docker pull ${{ env.OS_IMAGE_v1_6_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_6_x }} with ${{ steps.set_os_image.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ steps.set_os_image.outputs.osImage }} daemon://docker.io/${{ env.OS_IMAGE_v1_6_x }} --type=rpm --output=diff-result.txt
          cat diff-result.txt

  fetch-v1-5-x-diff:
    needs: get-all-releases
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/bci-base:15.5

    steps:
      - name: Set osImage
        id: set_os_image
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const osImage = `rancher/harvester-os:${{ needs.get-all-releases.outputs.releaseName_v1_5_x }}`;
            core.setOutput('osImage', osImage);
      - name: Install docker
        run: zypper ref && zypper -n install docker
      - name: Install container-diff
        run: |
          curl -sfL https://github.com/GoogleContainerTools/container-diff/releases/download/v0.17.0/container-diff-linux-amd64 -o /usr/bin/container-diff
          chmod +x /usr/bin/container-diff
      - name: Pull release image
        run: |
          docker pull ${{ steps.set_os_image.outputs.osImage }}
      - name: Run container-diff for v1.5.x
        run: |
          docker pull ${{ env.OS_IMAGE_v1_5_x }}
          echo "Diff ${{ env.OS_IMAGE_v1_5_x }} with ${{ steps.set_os_image.outputs.osImage }}..."
          container-diff diff daemon://docker.io/${{ steps.set_os_image.outputs.osImage }} daemon://docker.io/${{ env.OS_IMAGE_v1_5_x }} --type=rpm --output=diff-result.txt
          cat diff-result.txt
