on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean

env:
  repo: "rancher"
  OSImageName: "harvester-os"
  NVDriverToolkitImageName: "harvester-nvidia-driver-toolkit"

jobs:
  build-os-related-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 

    - name: Read some Secrets
      uses: rancher-eio/read-vault-secrets@main
      if: ${{ inputs.push == true }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ inputs.push == true }}
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: generate os-release
      run: bash scripts/ci

    - name: Docker Build (OS Image)
      uses: docker/build-push-action@v5
      with:
        provenance: false
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        push: ${{ inputs.push }}
        tags: ${{ env.repo }}/${{ env.OSImageName }}:${{ inputs.tag }}